blueprints/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, logout_user
from builder_service import db, User, check_and_log_user, CAPTCHA_SERVER_KEY, CAPTCHA_WEBSITE_KEY
import requests
import json

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return render_template('login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    username = request.form.get('username')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False
    if check_and_log_user(username, password, remember):
        return redirect(url_for('dashboard.home'))
    else:
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) 
    
   

@auth.route('/signup')
def signup():
    return render_template('signup.html', web_site_key=CAPTCHA_WEBSITE_KEY)

@auth.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    username = request.form.get('username')
    password = request.form.get('password')
    retype_password = request.form.get('retype_password')
    captcha_response = request.form.get('g-recaptcha-response')
    if captcha_response is None:
        flash("Please, validate captcha")
        return redirect(url_for('auth.signup'))
    if not captcha_validation(captcha_response):
        flash("Please, incorrect captcha validation")
        return redirect(url_for('auth.signup'))
    if username is None or password is None or retype_password is None or email is None:
        flash('Email, username or password is not provided')
        return redirect(url_for('auth.signup'))    
    if User.query.filter_by(username=username).first() is not None:
        flash('User already exists')
        return redirect(url_for('auth.signup'), login=True)  
    user = User(username=username, email=email)
    user.hash_password(password)
    db.session.add(user)
    db.session.commit()
    return redirect(url_for('auth.login'))

def captcha_validation(captcha_response):
    secret = CAPTCHA_SERVER_KEY
    payload = {'response':captcha_response, 'secret':secret}
    response = requests.post("https://www.google.com/recaptcha/api/siteverify", payload)
    response_text = json.loads(response.text)
    print("reCaptcha Response: " + str(response_text))
    return response_text['success']


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash("Logout Successful")
    return redirect(url_for('auth.login'))

blueprints/dashboard.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, Response, session
from flask_login import login_required, current_user
from builder_service import db, Build, Image, User, build_image, get_build_logs_path, remove_build, remove_image
from image_builder.utils import SPACK_ARCHITECTURES
import time

dashboard = Blueprint('dashboard', __name__)

@dashboard.route('/home')
@login_required
def home():
    return render_template('main.html')

@dashboard.route('/')
@login_required
def index():
    return render_template('main.html')

@dashboard.route('/builds', methods=['GET'])
@login_required
def get_builds():
    user = User.query.get(current_user.id)
    return render_template('builds.html', builds=user.builds)

@dashboard.route('/builds/<id>', methods=['GET'])
@login_required
def get_build(id):
     build = Build.query.get(id)
     return render_template('build_details.html', build=build)

@dashboard.route('/builds/<id>/logs', methods=['GET'])
@login_required
def get_build_logs(id):
     return render_template('logs.html', id=id)

@dashboard.route('/builds/<id>/logs/stream', methods=['GET'])
@login_required
def logs_stream(id):
    logs_file = get_build_logs_path(id)
    def generate():
        with open(logs_file) as f:        
            for line in f:
                yield line
    return Response(generate(), mimetype='text/plain')

@dashboard.route('/builds/<id>/delete')
@login_required
def delete_build(id):
     #TODO: cancel execution
     remove_build(id)
     build = db.session.query(Build).get(id)
     db.session.delete(build)
     db.session.commit()
     return redirect(url_for('dashboard.get_builds'))

@dashboard.route('/builds/new')
@login_required
def new_build():
    return render_template('request.html', architectures=SPACK_ARCHITECTURES)


@dashboard.route('/builds/new', methods=['POST'])
@login_required
def run_build():
    try:
        machine = {}
        machine['platform'] = request.form.get('platform')
        machine['architecture'] = request.form.get('cpu_architecture').strip()
        machine['container_engine'] = request.form.get('container_engine')
        machine['mpi'] = request.form.get('mpi').strip()
        machine['gpu'] = request.form.get('gpu').strip()
        wf_name = request.form.get('wf_name').strip()
        wf_step = request.form.get('wf_step').strip()
        version = request.form.get('wf_version').strip()
        if version is None or version == "" :
            version = 'latest'
        force = False
        push = True
        build_id = build_image (wf_name, wf_step, version, machine, force, push, current_user)
        return redirect(url_for('dashboard.get_build', id=build_id))
    except Exception as e:
        flash("Error submitting request" + str(e))
        return render_template('request.html', architectures=SPACK_ARCHITECTURES, form=request.form)


@dashboard.route('/images')
@login_required
def get_images(clean=True):
    if clean:
        session.pop('_flashes', None)
    images = Image.query.all()
    return render_template('images.html', images=images)

@dashboard.route('/images/delete')
@login_required
def delete_image():
    id = request.args.get('id')
    filename = request.args.get('filename')
    if id is None:
        flash("Id is None")
    else : 
        try:
            remove_image(id, filename)
        except Exception as e:
            flash("Error deleting image" + str(e))
        image = db.session.query(Image).get(id)
        db.session.delete(image)
        db.session.commit()
    return get_images(clean=False)

@dashboard.route('/account/token', methods=['POST'])
@login_required
def generate_token():
    token = current_user.generate_auth_token()
    return render_template('account.html', token=token)

@dashboard.route('/account')
@login_required
def account():
    return render_template('account.html', name=current_user.username)

@dashboard.route('/account/update', methods=['POST'])
@login_required
def update_password():
    new_password = request.form.get('new_password')
    retype_password = request.form.get('retype_password')
    if new_password == retype_password:
        current_user.hash_password(new_password)
        db.commit()
    else:
        flash("Password and retype are not the same")
    return render_template('account.html', password=True)

blueprints/download.py
from flask import Blueprint, send_file, abort
from builder_service import image_path

download = Blueprint('download', __name__)

@download.route('/images/download/<name>')
def download_image (name):
    path = image_path(name)
    if path is None:
        abort(404, "File " + name + " not found" )
    return send_file(path, as_attachment=True)

blueprints/images.py
from flask import Blueprint, request, jsonify, abort, g
from builder_service import build_image, get_build, auth
from image_builder.utils import check_bool
api = Blueprint('api', __name__)

@api.route('/build/', methods= ['POST'])
@auth.login_required
def build():
    content = request.json
    print("Request received: " + str(content))
    
    try:
        force = check_bool(content, 'force', False)
        push = check_bool(content, 'push', True)
        machine = content['machine']
        workflow = content['workflow']
        step_id = content['step_id']
        if 'version' in content:
            version = content['version']
        else:
            version = 'latest'
        build_id = build_image(workflow, step_id, version, machine, force, push, g.user)
        return jsonify({"id" : build_id})
    except KeyError as e:
        abort(400, "Bad request: Key error" + str(e))
    except Exception as e:
        abort(500, "Exception requesting image creation" + str(e))

@api.route('/build/<id>', methods=['GET'])
@auth.login_required
def check (id):
    build = get_build(id)
    if build is not None:
        return {"status" : build.status, "image_id" : build.image , "filename": build.filename, "message": build.message }
    else:
        abort(400, "Build not found")

templates/account.html
{% extends "dashboard.html" %}

{% block dashboard %}
<h1 class="title">{{name}} account management</h1>
<a class="button is-small" href="{{ url_for('dashboard.home') }}"><i class="fas fa-home"></i>&nbsp Home</a>
<div class="card">
    <div class="card-header">
        <p class="card-header-title">Password Update</p>
    </div>
    <div class="card-content">
        <div class="content">
            {% if password %}
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}.
            </div>
            {% else %}
            <div class="notification is-sucess is-light">
                Password succesfully changed.
            </div>
            {% endif %}
            {% endwith %}
            {% endif %}
            <form method="POST" action="{{ url_for('dashboard.update_password') }}">
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="password" name="new_password" placeholder="New Password">
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="password" name="old_password" placeholder="Retype Password">
                    </div>
                </div>

                <button class="button is-block is-info is-large is-fullwidth">Update</button>
            </form>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-header">
        <p class="card-header-title">Generate API Token</p>
    </div>
    <div class="card-content">
        <div class="content">
            {% if token %}
            Generated token:
            <div class="notification is-sucess is-light">
                {{token}}
            </div>
            {% endif %}
            <form method="POST" action="{{ url_for('dashboard.generate_token') }}">

                <button class="button is-block is-info is-large is-fullwidth">Generate</button>
            </form>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-header">
        <p class="card-header-title">Session</p>
    </div>
    <div class="card-content">
        <div class="content">
            <form method="GET" action="{{ url_for('auth.logout') }}">
                <button class="button is-block is-info is-large is-fullwidth"><i class="fas fa-sign-out-alt"></i>&nbsp Logout</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/base copy.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>
    
</head>
<style>
.button.is-orange{
    background-color: #ff8606;
    border-color: transparent;
    color: #fff;
}
</style>
<!--script src='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/js/all.min.js'>
</script-->
<body>
    <nav class="navbar is-info has-shadow">
            <div class="navbar-brand">
                <a class="navbar-item" href="https://eflows4hpc.eu/">
                    <img loading="lazy" width="210" height="60" src="https://eflows4hpc.eu/wp-content/uploads/2021/02/logo-blanc_1-1.svg">
                </a>
                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarMenuHeroA">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            
            
            <div id="navbarMenuHeroA" class="navbar-menu">
                <div class="navbar-end">
                    <a href="{{ url_for('dashboard.profile') }}" class="navbar-item">
                        Dashboard
                    </a>
                    <a href="{{ url_for('auth.login') }}" class="navbar-item">
                        Login
                    </a>
                    <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                        Sign Up
                    </a>
                    <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                        Logout
                    </a>
                </div>
            </div>
    </nav>
    <section class="main-content columns is-fullwidth is-fullheight">


                <aside class="column is-3 is-narrow-mobile is-fullheight section is-hidden-mobile">
                    <p class="menu-label is-hidden-touch">Navigation</p>
                    <ul class="menu-list">
                      <li>
                        <a href="#" class="">
                          <span class="icon"><i class="fas fa-home"></i></span> Home
                        </a>
                      </li>
                      <li>
                        <a href="#" class="">
                          <span class="icon"><i class="fas fa-cog"></i></span> Builds
                        </a>
                      </li>
                      <li>
                        <a href="#" class="">
                          <span class="icon"><i class="fas fa-layer-group"></i></span> Images
                        </a>
                      </li>
                      <li>
                        <a href="#" class="">
                          <span class="icon"><i class="fas fa-user"></i></span> Account
                        </a>
                      </li>
                    </ul>
                </aside>
                
                <div class="section column is-9">
                        <h1 class="title">Welcome {{name}} to the eflows4HPC Container Image Creation Service</h1>
                        <div class="columns">
                            <div class="column">
                                <a href="#" class="button is-orange is-large column">
                                Build requests
                                </a>
                            </div>
                            <div class="column">
                                <a href="#" class="button is-orange is-large column">
                                Available Images
                                </a>
                            </div>
                        </div>
                        
                </div>
                  
            <!--/div>
        </div-->
    </section>
</body>

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>eFlows4HPC Image Creation service</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>
</head>
<style>
.button.is-orange{
    background-color: #ff8606;
    border-color: transparent;
    color: #fff;
}
.select, .select select { 
    width: 100%;
}
</style>
<body>
    <nav class="navbar is-info has-shadow">
            <div class="navbar-brand">
                <a class="navbar-item" href="https://eflows4hpc.eu/">
                    <img loading="lazy" width="210" height="60" src="https://eflows4hpc.eu/wp-content/uploads/2021/02/logo-blanc_1-1.svg">
                </a>
                <!--<a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarMenuHeroA">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a-->
            </div>
            
            
            <div id="navbarMenuHeroA" class="navbar-menu">
                <div class="navbar-end">
                    {% if current_user.is_authenticated %}
                    <a href="{{ url_for('dashboard.home') }}" class="navbar-item">
                        Dashboard
                    </a>
                    <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                        Logout
                    </a>
                    {% endif %}
                    {% if not current_user.is_authenticated %}
                    <a href="{{ url_for('auth.login') }}" class="navbar-item">
                        Login
                    </a>
                    <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                        Sign Up
                    </a>
                    {% endif %}
                </div>
            </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>

templates/build_details.html
{% extends "dashboard.html" %}

{% block dashboard %}
<h1 class="title">Build Request {{build.id}} </h1>
<a class="button is-small" href="{{ url_for('dashboard.get_builds') }}">Builds</a>
<a class="button is-small" href="{{ url_for('dashboard.get_build', id=build.id) }}"><i class="fas fa-sync-alt"></i>&nbsp Refresh</a>
{% if build.status != 'PENDING'%}
    <a class="button is-small" href="{{url_for('dashboard.get_build_logs', id=build.id)}}">Logs</a>
{% endif %}
 <a class="button is-small" href="{{url_for('dashboard.delete_build', id=build.id)}}"><i class="fas fa-trash-alt"></i></a>

<div class="card"><div class="card-header">
    <p class="card-header-title">Build Description</p>
</div>

<div class="card-content">
    <div class="content">
        <div class="field">
            <label>Image ID: {{build.image}}</label>
        </div>
        <div class="field">
            <label>Status: {{build.status}}</label>
        </div>
        <div class="field">
            <label>Messages: {{build.message}}</label>
        </div>
        <div class="field">
            <label>Singularity file: {{build.filename}}</label>
        </div>  
    </div>
</div>
    <div class="card"><div class="card-header">
        <p class="card-header-title">Machine Description</p>
    </div>
    <div class="card-content">
        <div class="content">
            <div class="field">
                <label>Platorm: {{build.machine.platform}}</label>
            </div>
            <div class="field">
                <label>Processor Architecture: {{build.machine.architecture}}</label>
            </div>
            <div class="field">
                <label>MPI: {{build.machine.mpi}}</label>
            </div>
            <div class="field">
                <label>GPU: {{build.machine.gpu}}</label>
            </div>  
        </div>
    </div>
</div>
<div class="card">
    <div class="card-header">
        <p class="card-header-title">Workflow Reference</p>
    </div>
    <div class="card-content">
        <div class="content">
            <div class="field">
                <label>Workflow Name: {{build.workflow.name}}</label>
            </div>
            <div class="field">
                <label>Workflow Step: {{build.workflow.step}}</label>
            </div>
            <div class="field">
                <label>Version: {{build.workflow.version}}</label>
            </div>

        </div>
    </div>
</div>



{% endblock %}

templates/builds.html
{% extends "dashboard.html" %}

{% block dashboard %}
<h1 class="title">Requested Image Creations Service</h1>
<a class="button is-small" href="{{ url_for('dashboard.new_build') }}"><i class="fas fa-plus"></i>&nbsp New Request</a>
<a class="button is-small" href="{{ url_for('dashboard.get_builds') }}"><i class="fas fa-sync-alt"></i>&nbsp Refresh</a>
<a class="button is-small" href="{{ url_for('dashboard.home') }}"><i class="fas fa-home"></i>&nbsp Home</a>
<table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Image Identifier</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for build in builds %}
        <tr>
          <td>{{ build.id }}</td>
          <input type="hidden" name="build_id" value="{{ build.id }}">
          <td>{{ build.image }}</td>
          <td>{{ build.status }}</td>
          <td>
            <a class="button is-small" href="{{url_for('dashboard.get_build', id=build.id)}}">Details</a>
            {% if build.status != 'PENDING'%}
            <a class="button is-small" href="{{url_for('dashboard.get_build_logs', id=build.id)}}">Logs</a>
            {% endif %}
            <a class="button is-small" href="{{url_for('dashboard.delete_build', id=build.id)}}"><i class="fas fa-trash-alt"></i></a>
          </td>
          
        </tr>
      {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/dashboard.html
{% extends "base.html" %}

{% block content %}
<section class="main-content columns is-fullwidth is-fullheight">
    <aside class="column is-3 is-narrow-mobile is-fullheight section is-hidden-mobile">
        <p class="menu-label is-hidden-touch">Navigation</p>
        <ul class="menu-list">
          <li>
            <a href="{{ url_for('dashboard.home') }}" class="">
              <span class="icon"><i class="fas fa-home"></i></span> Home
            </a>
          </li>
          <li>
            <a href="{{ url_for('dashboard.get_builds') }}" class="">
              <span class="icon"><i class="fas fa-cog"></i></span> Builds
            </a>
          </li>
          <li>
            <a href="{{ url_for('dashboard.get_images') }}" class="">
              <span class="icon"><i class="fas fa-layer-group"></i></span> Images
            </a>
          </li>
          <li>
            <a href="{{ url_for('dashboard.account') }}" class="">
              <span class="icon"><i class="fas fa-user"></i></span> Account
            </a>
          </li>
        </ul>
    </aside>
    
    <div class="section column is-9">
        {% block dashboard %}
        {% endblock %}
    </div>
</section>
{% endblock %}

templates/images.html
{% extends "dashboard.html" %}

{% block dashboard %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="notification is-danger">
    {{ messages[0] }}.
</div>
{% endif %}
{% endwith %}
<h1 class="title">Available Images</h1>
<a class="button is-small" href="{{ url_for('dashboard.get_images') }}"><i class="fas fa-sync-alt"></i>&nbsp Refresh</a>
<a class="button is-small" href="{{ url_for('dashboard.home') }}"><i class="fas fa-home"></i>&nbsp Home</a>
<table class="table">
    <thead>
      <tr>
        <th>Image Identifier</th>
        <th>Singularity</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for image in images %}
        <tr>
          <th>{{image.id}}</th>
          {% if image.filename%}
          <td>{{image.filename}}</td>
          <td>
            <a class="button is-small" href="images/download/{{image.filename}}"><i class="fas fa-download"></i></a>
            <a class="button is-small" href="{{url_for('dashboard.delete_image', id=image.id, filename=image.filename)}}"><i class="fas fa-trash-alt"></i></a>
          </td>
          {% else %}
          <td></td>
          <td><a class="button is-small" href="{{url_for('dashboard.delete_image', id=image.id)}}"><i class="fas fa-trash-alt"></i></a></td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/logs.html
{% extends "dashboard.html" %}

{% block dashboard %}
<h1 class="title">Image Creation Logs for build {{id}}</h1>
<a class="button is-small" href="{{ url_for('dashboard.home') }}"><i class="fas fa-home"></i>&nbsp Home</a>
<a class="button is-small" href="{{ url_for('dashboard.get_build', id=id) }}"><i class="fas fa-info"></i>&nbsp Details</a>
<a class="button is-small" onclick="update()"><i class="fas fa-sync-alt"></i>&nbsp Refresh</a>
<pre id="output"></pre>
<a class="button is-small" onclick="update()"><i class="fas fa-sync-alt"></i>&nbsp Refresh</a>
<script>
    var output = document.getElementById('output');
    
    function update(){
      var xhr = new XMLHttpRequest();
      xhr.onloadend = function(){
      output.textContent = xhr.responseText;
      }
      xhr.open('GET', '{{ url_for('dashboard.logs_stream', id=id) }}');
      xhr.send();
    }
    update()
    /*setInterval(function(){
      output.textContent = xhr.responseText;
      }, 1000);*/
</script>

{% endblock %}

templates/main.html
{% extends "dashboard.html" %}

{% block dashboard %}
<h1 class="title">Welcome {{name}} to the eflows4HPC Container Image Creation Service</h1>
<div class="columns">
    <div class="column">
        <a href="{{url_for('dashboard.new_build')}}" class="button is-orange is-large column">
            New request
        </a>
        
    </div>
    <div class="column">
        <a href="{{url_for('dashboard.get_builds')}}" class="button is-orange is-large column">
            Build requests
        </a>
    </div>
</div>
<div class="columns">
        <div class="column">
            <a href="{{url_for('dashboard.get_images')}}" class="button is-orange is-large column">
                Available Images
            </a>
        </div>
        <div class="column">
            <a href="{{ url_for('dashboard.account') }}" class="button is-orange is-large column">
                Account Configuration
            </a>
        </div>
</div>
{% endblock %}

templates/request.html
{% extends "dashboard.html" %}

{% block dashboard %}
<h1 class="title">New Container Image Build Request</h1>

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="notification is-danger">
    {{ messages[0] }}.
</div>
{% endif %}
{% endwith %}
<a class="button is-small" href="{{ url_for('dashboard.home') }}"><i class="fas fa-home"></i>&nbsp Home</a>
<form method="POST" action="{{ url_for('dashboard.run_build') }}">
    <div class="card">
        <div class="card-header">
            <p class="card-header-title">Machine Description</p>
        </div>
        <div class="card-content">
            <div class="content">
                <div class="field">
                    <div class="select is-large">
                        <select name="platform" placeholder="System Platform" required>
                            <option disabled selected value="None">-- System Platform --</option>
                            <option value="linux/amd64">linux/amd64</option>
                            <option value="linux/ppc64le">linux/ppc64le</option>
                            <option value="linux/arm64/v8">linux/arm64/v8</option>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <div class="select is-large">
                        <select name="cpu_architecture" placeholder="Processor Architecture" required>
                            <option disabled selected value="None" label="-- Processor Architecture --"></option>
                            {% for architecture in architectures %}
                                <option value="{{ architecture }}" label="{{ architecture }}"></option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="field">
                    <div class="select is-large">
                        <select name="container_engine" placeholder="Container Engine" required>
                            <option disabled selected value="None">-- Container Engine --</option>
                            <option value="docker">Docker</option>
                            <option value="singularity">Singularity</option>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="" name="mpi" placeholder="MPI version (Optional)">
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="" name="gpu" placeholder="GPU runtime (Optional)">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <p class="card-header-title">Workflow Reference</p>
        </div>
        <div class="card-content">
            <div class="content">
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="" name="wf_name" placeholder="Workflow Name" required>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="" name="wf_step" placeholder="Sub-workflow Name" required>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input class="input is-large" type="" name="wf_version" placeholder="Workflow Version (Optional. Default latest)">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <button class="button is-block is-info is-large is-fullwidth">Build</button>
</form>


{% endblock %}